2018-11-27 15:23:15,401 ERROR: Exception on /generate_new_floorplans/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 66, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 590, in generate
    user_base_aspect_dict = map_user_selection(user_selections_obj,user_selections_rooms)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 409, in map_user_selection
    for obj in user_selections_obj[feedback_index]: #search through list of selected obj from the given loop
IndexError: list index out of range
2018-11-27 15:23:37,580 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-27 15:23:48,110 ERROR: Exception on /generate_new_floorplans/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 64, in generate_new_floorplans
    user_selections_obj.append(id_to_obj(Pt,user_selections))
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 425, in id_to_obj
    if int(selected_room[0]) == obj.plan_id: #finds user selection in pop based on ID
KeyError: 0
2018-11-27 15:43:35,371 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-27 15:48:36,207 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-27 15:49:08,511 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-27 15:54:06,065 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-27 15:54:59,742 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-27 15:57:13,636 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-27 16:02:31,977 ERROR: Exception on /generate_new_floorplans/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 66, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 591, in generate
    evaluate_pop(Pt,user_selections_obj, user_base_aspect_dict)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 126, in evaluate_pop
    individual.base_score[index] = individual.base_score[index] / max_base_dist[index]
ZeroDivisionError: division by zero
2018-11-27 16:02:33,719 ERROR: Exception on /generate_new_floorplans/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 66, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 591, in generate
    evaluate_pop(Pt,user_selections_obj, user_base_aspect_dict)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 126, in evaluate_pop
    individual.base_score[index] = individual.base_score[index] / max_base_dist[index]
ZeroDivisionError: division by zero
2018-11-27 16:05:39,533 ERROR: Exception on /generate_new_floorplans/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 66, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 591, in generate
    evaluate_pop(Pt,user_selections_obj, user_base_aspect_dict)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 126, in evaluate_pop
    individual.base_score[index] = individual.base_score[index] / max_base_dist[index]
ZeroDivisionError: division by zero
