<<<<<<< HEAD
2018-11-07 13:35:35,497 ERROR: Exception on /generate_lines/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
=======
2018-11-07 13:50:21,326 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-07 14:00:14,820 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-07 14:00:36,231 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-07 14:00:45,431 ERROR: Exception on /generate_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
>>>>>>> master
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
<<<<<<< HEAD
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 45, in generate_lines
    return jsonify(get_from_generation(generation,generation_rank))
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 434, in get_from_generation
    .order_by(Plan.pareto,Plan.crowding_score.desc()).all()[generation_rank]
AttributeError: type object 'Plan' has no attribute 'pareto'
2018-11-07 13:35:35,500 ERROR: Exception on /generate_lines/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
=======
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 35, in generate_floorplans
    init_population(user_selections,pop_size, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 392, in init_population
    objects_for_render(Pt)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 366, in objects_for_render
    for individual in newlist:
NameError: name 'newlist' is not defined
2018-11-07 14:01:46,842 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-07 14:01:54,950 ERROR: Exception on /generate_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
>>>>>>> master
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
<<<<<<< HEAD
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 45, in generate_lines
    return jsonify(get_from_generation(generation,generation_rank))
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 434, in get_from_generation
    .order_by(Plan.pareto,Plan.crowding_score.desc()).all()[generation_rank]
AttributeError: type object 'Plan' has no attribute 'pareto'
2018-11-07 13:35:35,505 ERROR: Exception on /generate_lines/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
=======
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 35, in generate_floorplans
    init_population(user_selections,pop_size, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 392, in init_population
    objects_for_render(Pt)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 366, in objects_for_render
    for individual in adjacenc_sorted:
NameError: name 'adjacenc_sorted' is not defined
2018-11-07 14:02:21,021 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-07 14:05:55,203 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-07 14:06:03,320 ERROR: Exception on /generate_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
>>>>>>> master
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
<<<<<<< HEAD
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 45, in generate_lines
    return jsonify(get_from_generation(generation,generation_rank))
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 434, in get_from_generation
    .order_by(Plan.pareto,Plan.crowding_score.desc()).all()[generation_rank]
AttributeError: type object 'Plan' has no attribute 'pareto'
=======
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 35, in generate_floorplans
    init_population(user_selections,pop_size, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 389, in init_population
    objects_for_render(Pt)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 365, in objects_for_render
    return [adjacency_sorted[0],interactive_sorted[0],aspects_sorted[0]]
NameError: name 'aspects_sorted' is not defined
2018-11-07 14:06:44,812 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
>>>>>>> master
2018-11-07 14:32:10,838 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:33:19,097 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:34:20,225 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:34:47,031 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:34:58,150 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:35:43,603 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:37:32,023 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:39:51,094 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:41:21,209 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:43:10,334 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:43:35,585 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:44:19,708 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:46:46,496 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:47:10,827 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-07 14:47:41,858 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
