2018-11-12 16:38:28,715 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 16:39:34,708 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 16:40:49,854 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 16:42:30,337 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 16:43:26,423 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 16:45:17,447 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 16:46:25,893 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 16:47:08,052 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 21:56:57,626 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 21:59:17,238 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:00:24,788 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:03:08,265 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:04:06,064 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:04:46,248 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:07:44,819 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:10:11,833 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:11:05,518 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:11:51,688 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:12:45,248 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:13:40,076 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:14:19,782 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:15:09,348 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:15:38,082 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:15:52,094 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:18:10,720 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:18:32,009 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:19:59,129 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:21:27,442 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:21:32,385 ERROR: Exception on /generate_first_floorplans/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 38, in generate_first_floorplans
    Pt = initial_generate(user_selections, pop_size, generations)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 423, in initial_generate
    select_objects_for_render(Pt)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 499, in select_objects_for_render
    adjacency_sorted = sorted(pareto_dict[pareto_front], key=lambda x: (x.interactive_score, x.dims_score, x.adjacency_score,  -x.crowding_score), reverse=False)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 499, in <lambda>
    adjacency_sorted = sorted(pareto_dict[pareto_front], key=lambda x: (x.interactive_score, x.dims_score, x.adjacency_score,  -x.crowding_score), reverse=False)
TypeError: bad operand type for unary -: 'list'
2018-11-12 22:22:24,386 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
2018-11-12 22:22:30,047 ERROR: Exception on /generate_first_floorplans/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 38, in generate_first_floorplans
    Pt = initial_generate(user_selections, pop_size, generations)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 423, in initial_generate
    select_objects_for_render(Pt)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 499, in select_objects_for_render
    adjacency_sorted = sorted(pareto_dict[pareto_front], key=lambda x: (x.interactive_score, x.dims_score, x.adjacency_score,  -x.crowding_score), reverse=False)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 499, in <lambda>
    adjacency_sorted = sorted(pareto_dict[pareto_front], key=lambda x: (x.interactive_score, x.dims_score, x.adjacency_score,  -x.crowding_score), reverse=False)
TypeError: bad operand type for unary -: 'list'
2018-11-12 22:22:38,321 ERROR: Exception on /generate_new_floorplans/ [POST] [in /Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Kristian/anaconda3/envs/py35/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/routes.py", line 55, in generate_new_floorplans
    Pt = generate(user_selections,generations)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 457, in generate
    select_objects_for_render(Pt)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 499, in select_objects_for_render
    adjacency_sorted = sorted(pareto_dict[pareto_front], key=lambda x: (x.interactive_score, x.dims_score, x.adjacency_score,  -x.crowding_score), reverse=False)
  File "/Users/Kristian/Documents/DTU/Thesis/generative/app/generative.py", line 499, in <lambda>
    adjacency_sorted = sorted(pareto_dict[pareto_front], key=lambda x: (x.interactive_score, x.dims_score, x.adjacency_score,  -x.crowding_score), reverse=False)
TypeError: bad operand type for unary -: 'list'
2018-11-12 22:23:12,708 INFO: Microblog startup [in /Users/Kristian/Documents/DTU/Thesis/generative/app/__init__.py:46]
