2018-11-30 20:26:24,769 ERROR: Exception on /generate_first_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 45, in generate_first_floorplans
    Pt = initial_generate(user_selections, pop_size, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 436, in initial_generate
    evaluate_pop(Pt,selections, selections) #correct this...
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 107, in evaluate_pop
    evaluate_layout(individual)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 95, in evaluate_layout
    get_layout(individual.definition, individual.room_def, individual.split_list, dir_pop, individual.room_order, individual.min_opening)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\space_planning.py", line 412, in get_layout
    all_adjacency_dict['Test2'].append(5)
KeyError: 'Test2'
2018-11-30 20:28:42,033 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-30 20:28:51,419 ERROR: Exception on /generate_first_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 45, in generate_first_floorplans
    Pt = initial_generate(user_selections, pop_size, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 436, in initial_generate
    evaluate_pop(Pt,selections, selections) #correct this...
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 107, in evaluate_pop
    evaluate_layout(individual)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 95, in evaluate_layout
    get_layout(individual.definition, individual.room_def, individual.split_list, dir_pop, individual.room_order, individual.min_opening)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\space_planning.py", line 412, in get_layout
    all_adjacency_dict['Test2'].append(5)
AttributeError: 'str' object has no attribute 'append'
2018-11-30 20:32:16,289 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-30 20:33:12,388 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-30 20:36:46,738 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-30 21:04:49,995 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
