2018-11-20 09:09:50,571 ERROR: Exception on /generate_new_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 58, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 548, in generate
    evaluate_pop(Pt,user_selections_obj, user_base_aspect_dict)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 127, in evaluate_pop
    individual.evaluate_user_input(user_input_dict_list)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 79, in evaluate_user_input
    print('user input room_list: ', room_list)
NameError: name 'room_list' is not defined
2018-11-20 09:10:38,557 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 10:51:41,327 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 10:52:15,166 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 10:54:26,117 ERROR: Exception on /generate_new_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 58, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 562, in generate
    evaluate_pop(Pt,user_selections_obj, user_base_aspect_dict)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 136, in evaluate_pop
    for index in range(len(user_input)):
UnboundLocalError: local variable 'user_input' referenced before assignment
2018-11-20 10:54:47,561 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 10:55:36,635 ERROR: Exception on /generate_new_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 58, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 562, in generate
    evaluate_pop(Pt,user_selections_obj, user_base_aspect_dict)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 138, in evaluate_pop
    individual.normalize_user_base(index,max_base_dist[index])
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 98, in normalize_user_base
    self.base_score[n] = self.base_score[n] / max_score
ZeroDivisionError: division by zero
2018-11-20 10:58:21,162 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 10:58:37,835 ERROR: Exception on /generate_new_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 58, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 565, in generate
    evaluate_pop(Pt,user_selections_obj, user_base_aspect_dict)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 141, in evaluate_pop
    individual.normalize_user_base(index,max_base_dist[index])
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 98, in normalize_user_base
    self.base_score[n] = self.base_score[n] / max_score
ZeroDivisionError: division by zero
2018-11-20 11:00:37,469 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 11:10:15,129 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 11:13:52,798 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 11:15:06,738 INFO: Microblog startup [in C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\__init__.py:46]
2018-11-20 11:19:50,387 ERROR: Exception on /generate_new_floorplans/ [POST] [in C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jalke\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\routes.py", line 58, in generate_new_floorplans
    Pt = generate(user_selections_obj,user_selections, generations)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 559, in generate
    evaluate_pop(Pt,user_selections_obj, user_base_aspect_dict)
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 138, in evaluate_pop
    individual.normalize_user_aspect(index,max_aspect[index])
  File "C:\Users\jalke\Documents\Kandidat\Speciale\generativedesign\app\generative.py", line 94, in normalize_user_aspect
    self.aspect_score[n] = self.aspect_score[n] / max_score
ZeroDivisionError: division by zero
